name: actions-config-validation
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write # enable write permissions for pull request comments

jobs:
  actions-config-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: actions-config-validation
        uses: GrantBirki/json-yaml-validate@3a3d883daf915618a7503a2e9c04b8e57130a4b8 # pin@v3.0.0
        with:
          comment: "true" # enable comment mode
          yaml_schema: "__tests__/schemas/action.schema.yml"
          exclude_file: ".github/config/exclude.txt"
